egor's first commit (add egorController)
matrosovcmtn/way pull request #2
Opened 2024-01-14 22:04 UTC by Belchonok31

2024-01-14 22:07 UTC, matrosovcmtn commented on pom.xml
> +		<java.version>18</java.version>
Не понял, что за произвол?) Почему версию поменял? Если у тебя нет 19 версии, ты можешь локально поменять это дело, но теперь ты всей команде версию джавы поменял) А это может всем все сломать

2024-01-14 22:07 UTC, matrosovcmtn commented on src/main/java/yourway/controllers/egorController.java
> +    public void hello(){
пробел после скобок

2024-01-14 22:08 UTC, matrosovcmtn commented on src/main/java/yourway/controllers/egorController.java
> +    public void hello(){
для этого ctrl+alt+L прожимай комбинацию, оно само выровняется

2024-01-14 22:08 UTC, matrosovcmtn commented on src/main/java/yourway/controllers/egorController.java
> +}
в конце всегда одна строка пустая

2024-01-14 22:09 UTC, Belchonok31 commented on pom.xml
> +		<java.version>18</java.version>
Бл так и знал, что не нужно это добавлять в коммит

2024-01-14 22:10 UTC, matrosovcmtn requested changes

2024-01-14 22:10 UTC, matrosovcmtn commented on src/main/java/yourway/controllers/egorController.java
> +    public void hello(){
Еще для того, чтобы убрать неиспользуемые импорты, можно прожать ctrl alt O

2024-01-15 08:49 UTC, matrosovcmtn approved these changes

2024-01-15 10:01 UTC, merged